spring.application.name=smart-revision-scheduler

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/smart_revision_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=112227
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Email / SMTP Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartrevisiontest@gmail.com
spring.mail.password=xxva jbmj cuka abvx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
gemini.api.key=AIzaSyB9mFt8AYZ2h132i8BVWu1s01C7WotYSRs